/**
 *  Built-in commands in Visual Studio Code.
 *  These commands are powered by the VS Code API and are available via the Command Palette.
 */
export const BuiltInCommands = {
  "Exit Zen Mode": "workbench.action.exitZenMode",
  "Close Reference Search": "closeReferenceSearch",
  "Close Test Peek": "editor.closeTestPeek",
  "Cancel Selection": "cancelSelection",
  "Move Cursor to Bottom": "cursorBottom",
  "Select Text to Bottom": "cursorBottomSelect",
  "Column Select Down": "cursorColumnSelectDown",
  "Column Select Left": "cursorColumnSelectLeft",
  "Column Select Page Down": "cursorColumnSelectPageDown",
  "Column Select Page Up": "cursorColumnSelectPageUp",
  "Column Select Right": "cursorColumnSelectRight",
  "Column Select Up": "cursorColumnSelectUp",
  "Move Cursor Down": "cursorDown",
  "Select Text Down": "cursorDownSelect",
  "Move Cursor to End": "cursorEnd",
  "Select Text to End": "cursorEndSelect",
  "Move Cursor to Home": "cursorHome",
  "Select Text to Home": "cursorHomeSelect",
  "Move Cursor Left": "cursorLeft",
  "Select Text Left": "cursorLeftSelect",
  "Move Cursor to Line End": "cursorLineEnd",
  "Select Text to Line End": "cursorLineEndSelect",
  "Move Cursor to Line Start": "cursorLineStart",
  "Select Text to Line Start": "cursorLineStartSelect",
  "Move Cursor Page Down": "cursorPageDown",
  "Select Text Page Down": "cursorPageDownSelect",
  "Move Cursor Page Up": "cursorPageUp",
  "Select Text Page Up": "cursorPageUpSelect",
  "Move Cursor Right": "cursorRight",
  "Select Text Right": "cursorRightSelect",
  "Move Cursor to Top": "cursorTop",
  "Select Text to Top": "cursorTopSelect",
  "Move Cursor Up": "cursorUp",
  "Select Text Up": "cursorUpSelect",
  "Delete Left": "deleteLeft",
  "Delete Right": "deleteRight",
  "Select All": "editor.action.selectAll",
  Copy: "execCopy",
  Cut: "execCut",
  Paste: "execPaste",
  "Expand Line Selection": "expandLineSelection",
  "Inline Chat Arrow Out Down": "inlineChat.arrowOutDown",
  "Inline Chat Arrow Out Up": "inlineChat.arrowOutUp",
  "Insert Line Break": "lineBreakInsert",
  Outdent: "outdent",
  Redo: "redo",
  "Scroll Line Down": "scrollLineDown",
  "Scroll Line Up": "scrollLineUp",
  "Scroll Page Down": "scrollPageDown",
  "Scroll Page Up": "scrollPageUp",
  Tab: "tab",
  Undo: "undo",
  "Remove Secondary Cursors": "removeSecondaryCursors",
  "Notebook Cell Chat Arrow Out Down": "notebook.cell.chat.arrowOutDown",
  "Notebook Cell Chat Arrow Out Up": "notebook.cell.chat.arrowOutUp",
  "Focus Chat Widget": "notebook.cell.focusChatWidget",
  "Focus Next Chat Widget": "notebook.cell.focusNextChatWidget",
  "Inline Chat Focus": "inlineChat.focus",
  "Accept Notebook Cell Chat Changes": "notebook.cell.chat.acceptChanges",
  "Next From Notebook Cell Chat History": "notebook.cell.chat.nextFromHistory",
  "Previous From Notebook Cell Chat History":
    "notebook.cell.chat.previousFromHistory",
  "Go To Next Reference": "goToNextReference",
  "Go To Previous Reference": "goToPreviousReference",
  "Apply Refactor Preview": "refactorPreview.apply",
  "Edit Focused Test": "testing.editFocusedTest",
  "Quit Notebook Cell Edit": "notebook.cell.quitEdit",
  "Discard Inline Chat": "inlineChat.discard",
  Find: "actions.find",
  "Find With Selection": "actions.findWithSelection",
  "Accept Breakpoint Widget Input": "breakpointWidget.action.acceptInput",
  "Focus Chat Action": "chat.action.focus",
  "Close Breakpoint Widget": "closeBreakpointWidget",
  "Cursor Undo": "cursorUndo",
  "Cursor Word End Right": "cursorWordEndRight",
  "Select Word End Right": "cursorWordEndRightSelect",
  "Cursor Word Left": "cursorWordLeft",
  "Select Word Left": "cursorWordLeftSelect",
  "Cursor Word Part Left": "cursorWordPartLeft",
  "Select Word Part Left": "cursorWordPartLeftSelect",
  "Cursor Word Part Right": "cursorWordPartRight",
  "Select Word Part Right": "cursorWordPartRightSelect",
  "Delete All Left": "deleteAllLeft",
  "Delete All Right": "deleteAllRight",
  "Delete Word Left": "deleteWordLeft",
  "Delete Word Part Left": "deleteWordPartLeft",
  "Delete Word Part Right": "deleteWordPartRight",
  "Delete Word Right": "deleteWordRight",
  "Next Accessible Diff Viewer": "editor.action.accessibleDiffViewer.next",
  "Previous Accessible Diff Viewer": "editor.action.accessibleDiffViewer.prev",
  "Add Comment Line": "editor.action.addCommentLine",
  "Add Selection To Next Find Match":
    "editor.action.addSelectionToNextFindMatch",
  "Auto Fix": "editor.action.autoFix",
  "Block Comment": "editor.action.blockComment",
  "Cancel Selection Anchor": "editor.action.cancelSelectionAnchor",
  "Change All": "editor.action.changeAll",
  "Clipboard Copy Action": "editor.action.clipboardCopyAction",
  "Clipboard Cut Action": "editor.action.clipboardCutAction",
  "Clipboard Paste Action": "editor.action.clipboardPasteAction",
  "Comment Line": "editor.action.commentLine",
  "Copy Lines Down Action": "editor.action.copyLinesDownAction",
  "Copy Lines Up Action": "editor.action.copyLinesUpAction",
  "Delete Lines": "editor.action.deleteLines",
  "Next Dirty Diff": "editor.action.dirtydiff.next",
  "Previous Dirty Diff": "editor.action.dirtydiff.previous",
  "Find Next in Extension Editor": "editor.action.extensioneditor.findNext",
  "Find Previous in Extension Editor":
    "editor.action.extensioneditor.findPrevious",
  "Show Find in Extension Editor": "editor.action.extensioneditor.showfind",
  "Format Document": "editor.action.formatDocument",
  "Format Selection": "editor.action.formatSelection",
  "Go To Bottom Hover": "editor.action.goToBottomHover",
  "Go To Focused Sticky Scroll Line":
    "editor.action.goToFocusedStickyScrollLine",
  "Go To Implementation": "editor.action.goToImplementation",
  "Go To References": "editor.action.goToReferences",
  "Go To Top Hover": "editor.action.goToTopHover",
  "Hide Color Picker": "editor.action.hideColorPicker",
  "In Place Replace Down": "editor.action.inPlaceReplace.down",
  "In Place Replace Up": "editor.action.inPlaceReplace.up",
  "Indent Lines": "editor.action.indentLines",
  "Reject Inline Edit": "editor.action.inlineEdit.reject",
  "Hide Inline Edits": "editor.action.inlineEdits.hide",
  "Show Next Inline Edits": "editor.action.inlineEdits.showNext",
  "Show Previous Inline Edits": "editor.action.inlineEdits.showPrevious",
  "Hide Inline Suggest": "editor.action.inlineSuggest.hide",
  "Show Next Inline Suggest": "editor.action.inlineSuggest.showNext",
  "Show Previous Inline Suggest": "editor.action.inlineSuggest.showPrevious",
  "Insert Color With Standalone Color Picker":
    "editor.action.insertColorWithStandaloneColorPicker",
  "Insert Cursor Above": "editor.action.insertCursorAbove",
  "Insert Cursor At End Of Each Line Selected":
    "editor.action.insertCursorAtEndOfEachLineSelected",
  "Insert Cursor Below": "editor.action.insertCursorBelow",
  "Insert Line After": "editor.action.insertLineAfter",
  "Insert Line Before": "editor.action.insertLineBefore",
  "Join Lines": "editor.action.joinLines",
  "Jump To Bracket": "editor.action.jumpToBracket",
  "Linked Editing": "editor.action.linkedEditing",
  "Next Marker": "editor.action.marker.next",
  "Next Marker In Files": "editor.action.marker.nextInFiles",
  "Previous Marker": "editor.action.marker.prev",
  "Previous Marker In Files": "editor.action.marker.prevInFiles",
  "Move Lines Down Action": "editor.action.moveLinesDownAction",
  "Move Lines Up Action": "editor.action.moveLinesUpAction",
  "Move Selection To Next Find Match":
    "editor.action.moveSelectionToNextFindMatch",
  "Next Comment Thread Action": "editor.action.nextCommentThreadAction",
  "Next Commenting Range": "editor.action.nextCommentingRange",
  "Next Match Find Action": "editor.action.nextMatchFindAction",
  "Next Selection Match Find Action":
    "editor.action.nextSelectionMatchFindAction",
  "Organize Imports": "editor.action.organizeImports",
  "Outdent Lines": "editor.action.outdentLines",
  "Page Down Hover": "editor.action.pageDownHover",
  "Page Up Hover": "editor.action.pageUpHover",
  "Peek Definition": "editor.action.peekDefinition",
  "Peek Implementation": "editor.action.peekImplementation",
  "Previous Comment Thread Action": "editor.action.previousCommentThreadAction",
  "Previous Commenting Range": "editor.action.previousCommentingRange",
  "Previous Match Find Action": "editor.action.previousMatchFindAction",
  "Previous Selection Match Find Action":
    "editor.action.previousSelectionMatchFindAction",
  "Quick Fix": "editor.action.quickFix",
  Refactor: "editor.action.refactor",
  "Remove Brackets": "editor.action.removeBrackets",
  "Remove Comment Line": "editor.action.removeCommentLine",
  Rename: "editor.action.rename",
  "Reveal Definition": "editor.action.revealDefinition",
  "Reveal definition": "editor.action.revealDefinition",
  "Reveal definition aside": "editor.action.revealDefinitionAside",
  "Scroll down hover": "editor.action.scrollDownHover",
  "Scroll left hover": "editor.action.scrollLeftHover",
  "Scroll right hover": "editor.action.scrollRightHover",
  "Scroll up hover": "editor.action.scrollUpHover",
  "Select editor": "editor.action.selectEditor",
  "Select from anchor to cursor": "editor.action.selectFromAnchorToCursor",
  "Select highlights": "editor.action.selectHighlights",
  "Select next sticky scroll line": "editor.action.selectNextStickyScrollLine",
  "Select previous sticky scroll line":
    "editor.action.selectPreviousStickyScrollLine",
  "Set selection anchor": "editor.action.setSelectionAnchor",
  "Show context menu": "editor.action.showContextMenu",
  "Show hover": "editor.action.showHover",
  "Expand smart select": "editor.action.smartSelect.expand",
  "Shrink smart select": "editor.action.smartSelect.shrink",
  "Start find replace action": "editor.action.startFindReplaceAction",
  "Submit comment": "editor.action.submitComment",
  "Toggle tab focus mode": "editor.action.toggleTabFocusMode",
  "Toggle word wrap": "editor.action.toggleWordWrap",
  "Transpose letters": "editor.action.transposeLetters",
  "Trigger parameter hints": "editor.action.triggerParameterHints",
  "Trigger suggest": "editor.action.triggerSuggest",
  "Trim trailing whitespace": "editor.action.trimTrailingWhitespace",
  "Find next in webview editor": "editor.action.webvieweditor.findNext",
  "Find previous in webview editor": "editor.action.webvieweditor.findPrevious",
  "Hide find in webview editor": "editor.action.webvieweditor.hideFind",
  "Show find in webview editor": "editor.action.webvieweditor.showFind",
  "Go to next word highlight": "editor.action.wordHighlight.next",
  "Go to previous word highlight": "editor.action.wordHighlight.prev",
  "Cancel operation": "editor.cancelOperation",
  "Change drop type": "editor.changeDropType",
  "Change paste type": "editor.changePasteType",
  "Create folding range from selection":
    "editor.createFoldingRangeFromSelection",
  "Close exception widget in debug action":
    "editor.debug.action.closeExceptionWidget",
  "Show debug hover in debug action": "editor.debug.action.showDebugHover",
  "Toggle breakpoint in debug action": "editor.debug.action.toggleBreakpoint",
  "Expand abbreviation in emmet action":
    "editor.emmet.action.expandAbbreviation",
  "Fold editor": "editor.fold",
  "Fold all in editor": "editor.foldAll",
  "Fold all block comments in editor": "editor.foldAllBlockComments",
  "Fold all except in editor": "editor.foldAllExcept",
  "Fold all marker regions in editor": "editor.foldAllMarkerRegions",
  "Fold level 1 in editor": "editor.foldLevel1",
  "Fold level 2 in editor": "editor.foldLevel2",
  "Fold level 3 in editor": "editor.foldLevel3",
  "Fold level 4 in editor": "editor.foldLevel4",
  "Fold level 5 in editor": "editor.foldLevel5",
  "Fold level 6 in editor": "editor.foldLevel6",
  "Fold level 7 in editor": "editor.foldLevel7",
  "Fold recursively in editor": "editor.foldRecursively",
  "Go to next symbol from result": "editor.gotoNextSymbolFromResult",
  "Cancel go to next symbol from result":
    "editor.gotoNextSymbolFromResult.cancel",
  "Hide drop widget": "editor.hideDropWidget",
  "Hide paste widget": "editor.hidePasteWidget",
  "Remove manual folding ranges": "editor.removeManualFoldingRanges",
  "Toggle fold in editor": "editor.toggleFold",
  "Toggle fold recursively in editor": "editor.toggleFoldRecursively",
  "Unfold editor": "editor.unfold",
  "Unfold all in editor": "editor.unfoldAll",
  "Unfold all except in editor": "editor.unfoldAllExcept",
  "Unfold all marker regions in editor": "editor.unfoldAllMarkerRegions",
  "Unfold recursively in editor": "editor.unfoldRecursively",
  "Stop reading line with hint": "inlayHints.stopReadingLineWithHint",
  "Insert snippet": "insertSnippet",
  "Execute in interactive": "interactive.execute",
  "Discard cell chat in notebook": "notebook.cell.chat.discard",
  "Cursor page down in notebook cell": "notebook.cell.cursorPageDown",
  "Cursor page down select in notebook cell":
    "notebook.cell.cursorPageDownSelect",
  "Cursor page up in notebook cell": "notebook.cell.cursorPageUp",
  "Cursor page up select in notebook cell": "notebook.cell.cursorPageUpSelect",
  "Execute notebook cell": "notebook.cell.execute",
  "Execute and insert below notebook cell":
    "notebook.cell.executeAndInsertBelow",
  "Execute and select below notebook cell":
    "notebook.cell.executeAndSelectBelow",
  "Paste above notebook cell": "notebook.cell.pasteAbove",
  "Focus next editor in notebook": "notebook.focusNextEditor",
  "Focus previous editor in notebook": "notebook.focusPreviousEditor",
  "Format cell in notebook": "notebook.formatCell",
  "Open reference to side": "openReferenceToSide",
  "Accept input in repl action": "repl.action.acceptInput",
  "Filter in repl action": "repl.action.filter",
  "Find in repl action": "repl.action.find",
  "Execute in repl": "repl.execute",
  "Rerun search editor search": "rerunSearchEditorSearch",
  "Focus query editor widget in search action":
    "search.action.focusQueryEditorWidget",
  "Delete file results in search editor action":
    "search.searchEditor.action.deleteFileResults",
  "Clear search results in settings action":
    "settings.action.clearSearchResults",
  "Focus settings file in settings action": "settings.action.focusSettingsFile",
  "Search in settings action": "settings.action.search",
  "Toggle explain mode": "toggleExplainMode",
  "Toggle peek widget focus": "togglePeekWidgetFocus",
  "Go back in welcome": "welcome.goBack",
  "Add comment in workbench action": "workbench.action.addComment",
  "Attach context in chat workbench action":
    "workbench.action.chat.attachContext",
  "Run in terminal in chat workbench action":
    "workbench.action.chat.runInTerminal",
  "Submit in chat workbench action": "workbench.action.chat.submit",
  "Submit secondary agent in chat workbench action":
    "workbench.action.chat.submitSecondaryAgent",
  "Go to next change in editor": "workbench.action.editor.nextChange",
  "Go to previous change in editor": "workbench.action.editor.previousChange",
  "Hide comment in workbench action": "workbench.action.hideComment",
  "Accept inline edit in editor": "editor.action.inlineEdit.accept",
  "Jump to inline edit in editor": "editor.action.inlineEdit.jumpTo",
  "Trigger inline edit in editor": "editor.action.inlineEdit.trigger",
  "Accept next word in inline suggest":
    "editor.action.inlineSuggest.acceptNextWord",
  "Go to next message in testing": "testing.goToNextMessage",
  "Go to previous message in testing": "testing.goToPreviousMessage",
  "Close find widget": "closeFindWidget",
  "Replace all in editor": "editor.action.replaceAll",
  "Replace one in editor": "editor.action.replaceOne",
  "Select all matches in editor": "editor.action.selectAllMatches",
  "Toggle find case sensitive": "toggleFindCaseSensitive",
  "Toggle find in selection": "toggleFindInSelection",
  "Toggle find regex": "toggleFindRegex",
  "Toggle find whole word": "toggleFindWholeWord",
  "Toggle preserve case": "togglePreserveCase",
  "Jump back in inline edit": "editor.action.inlineEdit.jumpBack",
  "Accept changes in notebook cell chat": "notebook.cell.chat.acceptChanges",
  "Jump to next snippet placeholder": "jumpToNextSnippetPlaceholder",
  "Jump to previous snippet placeholder": "jumpToPrevSnippetPlaceholder",
  "Leave editor message": "leaveEditorMessage",
  "Leave snippet": "leaveSnippet",
  "Close dirty diff": "closeDirtyDiff",
  "Close markers navigation": "closeMarkersNavigation",
  "Hide notifications toasts": "notifications.hideToasts",
  "Close parameter hints": "closeParameterHints",
  "Show next parameter hint": "showNextParameterHint",
  "Show previous parameter hint": "showPrevParameterHint",
  "Accept alternative selected suggestion":
    "acceptAlternativeSelectedSuggestion",
  "Accept selected suggestion": "acceptSelectedSuggestion",
  "Focus suggestion": "focusSuggestion",
  "Hide suggest widget": "hideSuggestWidget",
  "Insert best completion": "insertBestCompletion",
  "Insert next suggestion": "insertNextSuggestion",
  "Insert previous suggestion": "insertPrevSuggestion",
  "Select next page suggestion": "selectNextPageSuggestion",
  "Select next suggestion": "selectNextSuggestion",
  "Select previous page suggestion": "selectPrevPageSuggestion",
  "Select previous suggestion": "selectPrevSuggestion",
  "Toggle suggestion details": "toggleSuggestionDetails",
  "Toggle suggestion focus": "toggleSuggestionFocus",
  "Accept rename input": "acceptRenameInput",
  "Accept rename input with preview": "acceptRenameInputWithPreview",
  "Cancel linked editing input": "cancelLinkedEditingInput",
  "Cancel rename input": "cancelRenameInput",
  "Focus next rename suggestion": "focusNextRenameSuggestion",
  "Focus previous rename suggestion": "focusPreviousRenameSuggestion",
  "Add cursors at search results": "addCursorsAtSearchResults",
  "Focus breadcrumbs": "breadcrumbs.focus",
  "Focus and select breadcrumbs": "breadcrumbs.focusAndSelect",
  "Focus next breadcrumb": "breadcrumbs.focusNext",
  "Focus previous breadcrumb": "breadcrumbs.focusPrevious",
  "Reveal focused breadcrumb": "breadcrumbs.revealFocused",
  "Reveal focused breadcrumb from tree aside":
    "breadcrumbs.revealFocusedFromTreeAside",
  "Select focused breadcrumb": "breadcrumbs.selectFocused",
  "Toggle breadcrumbs to on": "breadcrumbs.toggleToOn",
  "Close replace in files widget": "closeReplaceInFilesWidget",
  "Clear filter text in comments": "commentsClearFilterText",
  "Focus on comments filter": "commentsFocusFilter",
  "Focus on view from comments filter": "commentsFocusViewFromFilter",
  "Copy file path": "copyFilePath",
  "Copy relative file path": "copyRelativeFilePath",
  "Open breakpoint to side in debug mode": "debug.openBreakpointToSide",
  "Open debug view": "debug.openView",
  "Remove breakpoint in debug mode": "debug.removeBreakpoint",
  "Remove watch expression in debug mode": "debug.removeWatchExpression",
  "Decrease search editor context lines": "decreaseSearchEditorContextLines",
  "Open accessibility help": "editor.action.accessibilityHelp",
  "Configure assigned keybindings for accessibility help":
    "editor.action.accessibilityHelpConfigureAssignedKeybindings",
  "Configure keybindings for accessibility help":
    "editor.action.accessibilityHelpConfigureKeybindings",
  "Open help link for accessibility help":
    "editor.action.accessibilityHelpOpenHelpLink",
  "Open accessible view": "editor.action.accessibleView",
  "Accept inline completion in accessible view":
    "editor.action.accessibleViewAcceptInlineCompletion",
  "Disable hint in accessible view": "editor.action.accessibleViewDisableHint",
  "Move to next in accessible view": "editor.action.accessibleViewNext",
  "Move to next code block in accessible view":
    "editor.action.accessibleViewNextCodeBlock",
  "Move to previous in accessible view": "editor.action.accessibleViewPrevious",
  "Move to previous code block in accessible view":
    "editor.action.accessibleViewPreviousCodeBlock",
  "Define keybinding in editor": "editor.action.defineKeybinding",
  "Commit inline suggestion in editor": "editor.action.inlineSuggest.commit",
  "Toggle inline breakpoint in debug editor":
    "editor.debug.action.toggleInlineBreakpoint",
  "Detect language in editor": "editor.detectLanguage",
  "Refocus call hierarchy in editor": "editor.refocusCallHierarchy",
  "Refocus type hierarchy in editor": "editor.refocusTypeHierarchy",
  "Show call hierarchy in editor": "editor.showCallHierarchy",
  "Show incoming calls in editor": "editor.showIncomingCalls",
  "Show outgoing calls in editor": "editor.showOutgoingCalls",
  "Show subtypes in editor": "editor.showSubtypes",
  "Show supertypes in editor": "editor.showSupertypes",
  "Open to side in explorer": "explorer.openToSide",
  "Find in folder in files explorer": "filesExplorer.findInFolder",
  "Show next in history": "history.showNext",
  "Show previous in history": "history.showPrevious",
  "Focus down in icon select box": "iconSelectBox.focusDown",
  "Focus next in icon select box": "iconSelectBox.focusNext",
  "Focus previous in icon select box": "iconSelectBox.focusPrevious",
  "Focus up in icon select box": "iconSelectBox.focusUp",
  "Select focused in icon select box": "iconSelectBox.selectFocused",
  "Increase search editor context lines": "increaseSearchEditorContextLines",
  "Close inline chat": "inlineChat.close",
  "Discard hunk change in inline chat": "inlineChat.discardHunkChange",
  "Hold for speech in inline chat": "inlineChat.holdForSpeech",
  "Move to next hunk in inline chat": "inlineChat.moveToNextHunk",
  "Move to previous hunk in inline chat": "inlineChat.moveToPreviousHunk",
  "Regenerate in inline chat": "inlineChat.regenerate",
  "Start inline chat": "inlineChat.start",
  "Unstash in inline chat": "inlineChat.unstash",
  "View in chat in inline chat": "inlineChat.viewInChat",
  "Show next in interactive history": "interactive.history.next",
  "Show previous in interactive history": "interactive.history.previous",
  "Scroll to bottom in interactive": "interactive.scrollToBottom",
  "Scroll to top in interactive": "interactive.scrollToTop",
  "Accept when expression in keybindings editor":
    "keybindings.editor.acceptWhenExpression",
  "Add keybinding in keybindings editor": "keybindings.editor.addKeybinding",
  "Clear search results in keybindings editor":
    "keybindings.editor.clearSearchResults",
  "Copy keybinding entry in keybindings editor":
    "keybindings.editor.copyKeybindingEntry",
  "Define keybinding in keybindings editor":
    "keybindings.editor.defineKeybinding",
  "Define when expression in keybindings editor":
    "keybindings.editor.defineWhenExpression",
  "Focus keybindings in keybindings editor":
    "keybindings.editor.focusKeybindings",
  "Record search keys in keybindings editor":
    "keybindings.editor.recordSearchKeys",
  "Reject when expression in keybindings editor":
    "keybindings.editor.rejectWhenExpression",
  "Remove keybinding in keybindings editor":
    "keybindings.editor.removeKeybinding",
  "Search keybindings in keybindings editor":
    "keybindings.editor.searchKeybindings",
  "Toggle sort by precedence in keybindings editor":
    "keybindings.editor.toggleSortByPrecedence",
  "Clear list": "list.clear",
  "Close find in list": "list.closeFind",
  "Collapse list": "list.collapse",
  "Collapse all in list": "list.collapseAll",
  "Expand list": "list.expand",
  "Expand selection down in list": "list.expandSelectionDown",
  "Expand selection up in list": "list.expandSelectionUp",
  "Find in list": "list.find",
  "Focus any down in list": "list.focusAnyDown",
  "Focus any first in list": "list.focusAnyFirst",
  "Focus any last in list": "list.focusAnyLast",
  "Focus any up in list": "list.focusAnyUp",
  "Focus down in list": "list.focusDown",
  "Focus first in list": "list.focusFirst",
  "Focus last in list": "list.focusLast",
  "Focus page down in list": "list.focusPageDown",
  "Focus page up in list": "list.focusPageUp",
  "Focus up in list": "list.focusUp",
  "Scroll down in list": "list.scrollDown",
  "Scroll up in list": "list.scrollUp",
  "Select in list": "list.select",
  "Select all in list": "list.selectAll",
  "Show hover in list": "list.showHover",
  "Toggle expand in list": "list.toggleExpand",
  "Toggle selection in list": "list.toggleSelection",
  "Delete left in note multi cursor": "noteMultiCursor.deleteLeft",
  "Exit note multi cursor": "noteMultiCursor.exit",
  "Add find match to selection in notebook": "notebook.addFindMatchToSelection",
  "Change to code in notebook cell": "notebook.cell.changeToCode",
  "Change to markdown in notebook cell": "notebook.cell.changeToMarkdown",
  "Accept chat in notebook cell": "notebook.cell.chat.accept",
  "Focus in notebook cell chat": "notebook.cell.chat.focus",
  "Focus next cell in notebook cell chat": "notebook.cell.chat.focusNextCell",
  "Focus previous cell in notebook cell chat":
    "notebook.cell.chat.focusPreviousCell",
  "Start notebook cell chat": "notebook.cell.chat.start",
  "Clear outputs in notebook cell": "notebook.cell.clearOutputs",
  "Collapse cell input in notebook cell": "notebook.cell.collapseCellInput",
  "Collapse cell output in notebook cell": "notebook.cell.collapseCellOutput",
  "Copy down in notebook cell": "notebook.cell.copyDown",
  "Copy up in notebook cell": "notebook.cell.copyUp",
  "Delete notebook cell": "notebook.cell.delete",
  "Detect language in notebook cell": "notebook.cell.detectLanguage",
  "Edit notebook cell": "notebook.cell.edit",
  "Expand cell input in notebook cell": "notebook.cell.expandCellInput",
  "Expand cell output in notebook cell": "notebook.cell.expandCellOutput",
  "Focus in output in notebook cell": "notebook.cell.focusInOutput",
  "Focus out output in notebook cell": "notebook.cell.focusOutOutput",
  "Insert code cell above in notebook cell":
    "notebook.cell.insertCodeCellAbove",
  "Insert code cell below in notebook cell":
    "notebook.cell.insertCodeCellBelow",
  "Join above in notebook cell": "notebook.cell.joinAbove",
  "Join below in notebook cell": "notebook.cell.joinBelow",
  "Move down in notebook cell": "notebook.cell.moveDown",
  "Move up in notebook cell": "notebook.cell.moveUp",
  "Open failure actions in notebook cell": "notebook.cell.openFailureActions",
  "Split notebook cell": "notebook.cell.split",
  "Toggle output scrolling in notebook cell":
    "notebook.cell.toggleOutputScrolling",
  "Center active cell in notebook": "notebook.centerActiveCell",
  "Comment selected cells in notebook": "notebook.commentSelectedCells",
  "Move to next action in notebook diff": "notebook.diff.action.next",
  "Move to previous action in notebook diff": "notebook.diff.action.previous",
  "Find in notebook": "notebook.find",
  "Focus bottom in notebook": "notebook.focusBottom",
  "Focus top in notebook": "notebook.focusTop",
  "Fold in notebook": "notebook.fold",
  "Format in notebook": "notebook.format",
  "Hide find in notebook": "notebook.hideFind",
  "Unfold in notebook": "notebook.unfold",
  "Accept primary action in notification": "notification.acceptPrimaryAction",
  "Clear notification": "notification.clear",
  "Collapse notification": "notification.collapse",
  "Expand notification": "notification.expand",
  "Toggle notification": "notification.toggle",
  "Focus first toast in notifications": "notifications.focusFirstToast",
  "Focus last toast in notifications": "notifications.focusLastToast",
  "Focus next toast in notifications": "notifications.focusNextToast",
  "Focus previous toast in notifications": "notifications.focusPreviousToast",
  "Show list in notifications": "notifications.showList",
  "Clear filter text in problems action": "problems.action.clearFilterText",
  "Copy in problems action": "problems.action.copy",
  "Focus filter in problems action": "problems.action.focusFilter",
  "Focus problems from filter in problems action":
    "problems.action.focusProblemsFromFilter",
  "Open in problems action": "problems.action.open",
  "Open to side in problems action": "problems.action.openToSide",
  "Show quick fixes in problems action": "problems.action.showQuickFixes",
  "Move to first in quick input": "quickInput.first",
  "Move to last in quick input": "quickInput.last",
  "Move to next in quick input": "quickInput.next",
  "Move to next separator in quick input": "quickInput.nextSeparator",
  "Move to next separator with quick access fallback in quick input":
    "quickInput.nextSeparatorWithQuickAccessFallback",
  "Page next in quick input": "quickInput.pageNext",
  "Go to next page in quick input": "quickInput.pageNext",
  "Go to previous page in quick input": "quickInput.pagePrevious",
  "Go to previous item in quick input": "quickInput.previous",
  "Go to previous separator in quick input": "quickInput.previousSeparator",
  "Toggle checked state in refactor preview":
    "refactorPreview.toggleCheckedState",
  "Reveal file in operating system": "revealFileInOS",
  "Reveal reference": "revealReference",
  "Save all files": "saveAll",
  "Accept input in source control": "scm.acceptInput",
  "Clear input in source control": "scm.clearInput",
  "Force view next commit in source control": "scm.forceViewNextCommit",
  "Force view previous commit in source control": "scm.forceViewPreviousCommit",
  "View next commit in source control": "scm.viewNextCommit",
  "View previous commit in source control": "scm.viewPreviousCommit",
  "Cancel search": "search.action.cancel",
  "Copy match in search": "search.action.copyMatch",
  "Copy path in search": "search.action.copyPath",
  "Focus next search result": "search.action.focusNextSearchResult",
  "Focus previous search result": "search.action.focusPreviousSearchResult",
  "Focus search from results": "search.action.focusSearchFromResults",
  "Open in editor from search": "search.action.openInEditor",
  "Open search result": "search.action.openResult",
  "Open search result to side": "search.action.openResultToSide",
  "Remove from search": "search.action.remove",
  "Replace in search": "search.action.replace",
  "Replace all in search": "search.action.replaceAll",
  "Replace all in file from search": "search.action.replaceAllInFile",
  "Replace all in folder from search": "search.action.replaceAllInFolder",
  "Restrict search to folder": "search.action.restrictSearchToFolder",
  "Focus next input box in search": "search.focus.nextInputBox",
  "Focus previous input box in search": "search.focus.previousInputBox",
  "Select all matches in search editor": "selectAllSearchEditorMatches",
  "Focus level up in settings": "settings.action.focusLevelUp",
  "Focus setting control in settings": "settings.action.focusSettingControl",
  "Focus settings from search": "settings.action.focusSettingsFromSearch",
  "Focus settings list in settings": "settings.action.focusSettingsList",
  "Focus table of contents in settings": "settings.action.focusTOC",
  "Show context menu in settings": "settings.action.showContextMenu",
  "Cancel test run": "testing.cancelRun",
  "Cover all tests": "testing.coverageAll",
  "Cover tests at cursor": "testing.coverageAtCursor",
  "Cover current file tests": "testing.coverageCurrentFile",
  "Cover last run tests": "testing.coverageLastRun",
  "Debug all tests": "testing.debugAll",
  "Debug tests at cursor": "testing.debugAtCursor",
  "Debug current file tests": "testing.debugCurrentFile",
  "Debug failed tests": "testing.debugFailTests",
  "Debug last run tests": "testing.debugLastRun",
  "Open output peek in tests": "testing.openOutputPeek",
  "Re-run failed tests": "testing.reRunFailTests",
  "Re-run last run tests": "testing.reRunLastRun",
  "Refresh tests": "testing.refreshTests",
  "Run all tests": "testing.runAll",
  "Run tests at cursor": "testing.runAtCursor",
  "Run current file tests": "testing.runCurrentFile",
  "Show most recent output in tests": "testing.showMostRecentOutput",
  "Toggle inline coverage in tests": "testing.toggleInlineCoverage",
  "Toggle inline test output in tests": "testing.toggleInlineTestOutput",
  "Toggle testing peek history": "testing.toggleTestingPeekHistory",
  "Toggle search case sensitivity": "toggleSearchCaseSensitive",
  "Toggle search editor case sensitivity": "toggleSearchEditorCaseSensitive",
  "Toggle search editor context lines": "toggleSearchEditorContextLines",
  "Toggle search editor regex": "toggleSearchEditorRegex",
  "Toggle search editor whole word": "toggleSearchEditorWholeWord",
  "Toggle search preserve case": "toggleSearchPreserveCase",
  "Toggle search regex": "toggleSearchRegex",
  "Toggle search whole word": "toggleSearchWholeWord",
  "Show new file entries in welcome": "welcome.showNewFileEntries",
  "Focus next widget": "widgetNavigation.focusNext",
  "Focus previous widget": "widgetNavigation.focusPrevious",
  "Cancel chat in workbench": "workbench.action.chat.cancel",
  "Focus input in chat": "workbench.action.chat.focusInput",
  "Hold to voice chat in chat view":
    "workbench.action.chat.holdToVoiceChatInChatView",
  "Start new chat": "workbench.action.chat.newChat",
  "Go to next code block in chat": "workbench.action.chat.nextCodeBlock",
  "Go to next file tree in chat": "workbench.action.chat.nextFileTree",
  "Open chat": "workbench.action.chat.open",
  "Go to previous code block in chat":
    "workbench.action.chat.previousCodeBlock",
  "Go to previous file tree in chat": "workbench.action.chat.previousFileTree",
  "Remove from chat": "workbench.action.chat.remove",
  "Send to new chat": "workbench.action.chat.sendToNewChat",
  "Start voice chat": "workbench.action.chat.startVoiceChat",
  "Stop listening and submit in chat":
    "workbench.action.chat.stopListeningAndSubmit",
  "Close active editor": "workbench.action.closeActiveEditor",
  "Close all editors": "workbench.action.closeAllEditors",
  "Close all groups": "workbench.action.closeAllGroups",
  "Close editors in group": "workbench.action.closeEditorsInGroup",
  "Close folder": "workbench.action.closeFolder",
  "Close group": "workbench.action.closeGroup",
  "Close other editors": "workbench.action.closeOtherEditors",
  "Close quick open": "workbench.action.closeQuickOpen",
  "Close unmodified editors": "workbench.action.closeUnmodifiedEditors",
  "Close window": "workbench.action.closeWindow",
  "Go to next change in compare editor":
    "workbench.action.compareEditor.nextChange",
  "Open side in compare editor": "workbench.action.compareEditor.openSide",
  "Go to previous change in compare editor":
    "workbench.action.compareEditor.previousChange",
  "Copy editor to new window": "workbench.action.copyEditorToNewWindow",
  "Disconnect debug": "workbench.action.debug.disconnect",
  "Restart debug": "workbench.action.debug.restart",
  "Run debug": "workbench.action.debug.run",
  "Start debug": "workbench.action.debug.start",
  "Step into target in debug": "workbench.action.debug.stepIntoTarget",
  "Step out in debug": "workbench.action.debug.stepOut",
  "Step over in debug": "workbench.action.debug.stepOver",
  "Stop debug": "workbench.action.debug.stop",
  "Change language mode in editor":
    "workbench.action.editor.changeLanguageMode",
  "Start dictation in editor": "workbench.action.editorDictation.start",
  "Copy path of active file": "workbench.action.files.copyPathOfActiveFile",
  "Create new untitled file": "workbench.action.files.newUntitledFile",
  "Open file": "workbench.action.files.openFile",
  "Open file or folder": "workbench.action.files.openFileFolder",
  "Open folder via workspace": "workbench.action.files.openFolderViaWorkspace",
  "Open local file or folder": "workbench.action.files.openLocalFileFolder",
  "Reveal active file in windows":
    "workbench.action.files.revealActiveFileInWindows",
  "Save file": "workbench.action.files.save",
  "Save file as": "workbench.action.files.saveAs",
  "Save local file": "workbench.action.files.saveLocalFile",
  "Save file without formatting":
    "workbench.action.files.saveWithoutFormatting",
  "Find in files": "workbench.action.findInFiles",
  "Focus above group": "workbench.action.focusAboveGroup",
  "Focus below group": "workbench.action.focusBelowGroup",
  "Focus eighth editor group": "workbench.action.focusEighthEditorGroup",
  "Focus fifth editor group": "workbench.action.focusFifthEditorGroup",
  "Focus first editor group": "workbench.action.focusFirstEditorGroup",
  "Focus fourth editor group": "workbench.action.focusFourthEditorGroup",
  "Focus left group": "workbench.action.focusLeftGroup",
  "Focus next part": "workbench.action.focusNextPart",
  "Focus previous part": "workbench.action.focusPreviousPart",
  "Focus right group": "workbench.action.focusRightGroup",
  "Focus second editor group": "workbench.action.focusSecondEditorGroup",
  "Focus seventh editor group": "workbench.action.focusSeventhEditorGroup",
  "Focus side bar": "workbench.action.focusSideBar",
  "Focus sixth editor group": "workbench.action.focusSixthEditorGroup",
  "Focus third editor group": "workbench.action.focusThirdEditorGroup",
  "Go to line": "workbench.action.gotoLine",
  "Go to symbol": "workbench.action.gotoSymbol",
  "Arrow down in interactive playground":
    "workbench.action.interactivePlayground.arrowDown",
  "Arrow up in interactive playground":
    "workbench.action.interactivePlayground.arrowUp",
  "Page down in interactive playground":
    "workbench.action.interactivePlayground.pageDown",
  "Page up in interactive playground":
    "workbench.action.interactivePlayground.pageUp",
  "Join editor in group": "workbench.action.joinEditorInGroup",
  "Keep editor": "workbench.action.keepEditor",
  "Open keybindings reference": "workbench.action.keybindingsReference",
  "Go to last editor in group": "workbench.action.lastEditorInGroup",
  "Move active editor group down": "workbench.action.moveActiveEditorGroupDown",
  "Move active editor group left": "workbench.action.moveActiveEditorGroupLeft",
  "Move active editor group right":
    "workbench.action.moveActiveEditorGroupRight",
  "Move active editor group up": "workbench.action.moveActiveEditorGroupUp",
  "Move editor left in group": "workbench.action.moveEditorLeftInGroup",
  "Move editor right in group": "workbench.action.moveEditorRightInGroup",
  "Move editor to first group": "workbench.action.moveEditorToFirstGroup",
  "Move editor to last group": "workbench.action.moveEditorToLastGroup",
  "Move editor to next group": "workbench.action.moveEditorToNextGroup",
  "Move editor to previous group": "workbench.action.moveEditorToPreviousGroup",
  "Navigate back": "workbench.action.navigateBack",
  "Navigate forward": "workbench.action.navigateForward",
  "Navigate to last edit location":
    "workbench.action.navigateToLastEditLocation",
  "Open new window": "workbench.action.newWindow",
  "Go to next editor": "workbench.action.nextEditor",
  "Go to next editor in group": "workbench.action.nextEditorInGroup",
  "Open editor at index 1": "workbench.action.openEditorAtIndex1",
  "Open editor at index 2": "workbench.action.openEditorAtIndex2",
  "Open editor at index 3": "workbench.action.openEditorAtIndex3",
  "Open editor at index 4": "workbench.action.openEditorAtIndex4",
  "Open editor at index 5": "workbench.action.openEditorAtIndex5",
  "Open editor at index 6": "workbench.action.openEditorAtIndex6",
  "Open editor at index 7": "workbench.action.openEditorAtIndex7",
  "Open editor at index 8": "workbench.action.openEditorAtIndex8",
  "Open editor at index 9": "workbench.action.openEditorAtIndex9",
  "Open global keybindings": "workbench.action.openGlobalKeybindings",
  "Open recent": "workbench.action.openRecent",
  "Open settings": "workbench.action.openSettings",
  "Toggle output": "workbench.action.output.toggleOutput",
  "Pin editor": "workbench.action.pinEditor",
  "Go to previous editor": "workbench.action.previousEditor",
  "Switch to previous editor in group":
    "workbench.action.previousEditorInGroup",
  "Quick open file": "workbench.action.quickOpen",
  "Open least recently used editor in group":
    "workbench.action.quickOpenLeastRecentlyUsedEditorInGroup",
  "Open previous recently used editor in group":
    "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
  "Quick open view": "workbench.action.quickOpenView",
  "Toggle quick chat": "workbench.action.quickchat.toggle",
  "Quit VS Code": "workbench.action.quit",
  "Show remote menu": "workbench.action.remote.showMenu",
  "Reopen closed editor": "workbench.action.reopenClosedEditor",
  "Replace in files": "workbench.action.replaceInFiles",
  "Toggle search query details": "workbench.action.search.toggleQueryDetails",
  "Select theme": "workbench.action.selectTheme",
  "Show all editors": "workbench.action.showAllEditors",
  "Show all symbols": "workbench.action.showAllSymbols",
  "Show commands": "workbench.action.showCommands",
  "Split editor": "workbench.action.splitEditor",
  "Split editor down": "workbench.action.splitEditorDown",
  "Split editor in group": "workbench.action.splitEditorInGroup",
  "Split editor left": "workbench.action.splitEditorLeft",
  "Split editor orthogonal": "workbench.action.splitEditorOrthogonal",
  "Split editor right": "workbench.action.splitEditorRight",
  "Split editor up": "workbench.action.splitEditorUp",
  "Switch window": "workbench.action.switchWindow",
  "Build tasks": "workbench.action.tasks.build",
  "Close terminal chat": "workbench.action.terminal.chat.close",
  "Focus terminal chat input": "workbench.action.terminal.chat.focusInput",
  "Focus terminal chat response":
    "workbench.action.terminal.chat.focusResponse",
  "Insert command in terminal chat":
    "workbench.action.terminal.chat.insertCommand",
  "Insert first command in terminal chat":
    "workbench.action.terminal.chat.insertFirstCommand",
  "Make request in terminal chat": "workbench.action.terminal.chat.makeRequest",
  "Next from history in terminal chat":
    "workbench.action.terminal.chat.nextFromHistory",
  "Previous from history in terminal chat":
    "workbench.action.terminal.chat.previousFromHistory",
  "Run command in terminal chat": "workbench.action.terminal.chat.runCommand",
  "Run first command in terminal chat":
    "workbench.action.terminal.chat.runFirstCommand",
  "Clear terminal selection": "workbench.action.terminal.clearSelection",
  "Copy terminal selection": "workbench.action.terminal.copySelection",
  "Find next in terminal": "workbench.action.terminal.findNext",
  "Find previous in terminal": "workbench.action.terminal.findPrevious",
  "Focus terminal": "workbench.action.terminal.focus",
  "Focus accessible buffer in terminal":
    "workbench.action.terminal.focusAccessibleBuffer",
  "Focus find in terminal": "workbench.action.terminal.focusFind",
  "Focus hover in terminal": "workbench.action.terminal.focusHover",
  "Focus next in terminal": "workbench.action.terminal.focusNext",
  "Focus next pane in terminal": "workbench.action.terminal.focusNextPane",
  "Focus previous in terminal": "workbench.action.terminal.focusPrevious",
  "Focus previous pane in terminal":
    "workbench.action.terminal.focusPreviousPane",
  "Focus tabs in terminal": "workbench.action.terminal.focusTabs",
  "Go to recent directory in terminal":
    "workbench.action.terminal.goToRecentDirectory",
  "Hide find in terminal": "workbench.action.terminal.hideFind",
  "Kill active tab in terminal": "workbench.action.terminal.killActiveTab",
  "Kill editor in terminal": "workbench.action.terminal.killEditor",
  "New terminal": "workbench.action.terminal.new",
  "Open native console in terminal":
    "workbench.action.terminal.openNativeConsole",
  "Paste in terminal": "workbench.action.terminal.paste",
  "Rename active tab in terminal": "workbench.action.terminal.renameActiveTab",
  "Resize pane down in terminal": "workbench.action.terminal.resizePaneDown",
  "Resize pane left in terminal": "workbench.action.terminal.resizePaneLeft",
  "Resize pane right in terminal": "workbench.action.terminal.resizePaneRight",
  "Resize pane up in terminal": "workbench.action.terminal.resizePaneUp",
  "Run recent command in terminal":
    "workbench.action.terminal.runRecentCommand",
  "Scroll down in terminal": "workbench.action.terminal.scrollDown",
  "Scroll down page in terminal": "workbench.action.terminal.scrollDownPage",
  "Scroll to bottom in terminal": "workbench.action.terminal.scrollToBottom",
  "Scroll to bottom accessible view in terminal":
    "workbench.action.terminal.scrollToBottomAccessibleView",
  "Scroll to next command in terminal":
    "workbench.action.terminal.scrollToNextCommand",
  "Scroll to previous command in terminal":
    "workbench.action.terminal.scrollToPreviousCommand",
  "Scroll to top in terminal": "workbench.action.terminal.scrollToTop",
  "Scroll to top accessible view in terminal":
    "workbench.action.terminal.scrollToTopAccessibleView",
  "Scroll up in terminal": "workbench.action.terminal.scrollUp",
  "Scroll up page in terminal": "workbench.action.terminal.scrollUpPage",
  "Select all in terminal": "workbench.action.terminal.selectAll",
  "Select to next command in terminal":
    "workbench.action.terminal.selectToNextCommand",
  "Select to previous command in terminal":
    "workbench.action.terminal.selectToPreviousCommand",
  "Send sequence in terminal": "workbench.action.terminal.sendSequence",
  "Show quick fixes in terminal": "workbench.action.terminal.showQuickFixes",
  "Size to content width in terminal":
    "workbench.action.terminal.sizeToContentWidth",
  "Split terminal": "workbench.action.terminal.split",
  "Split active tab in terminal": "workbench.action.terminal.splitActiveTab",
  "Toggle find case sensitive in terminal":
    "workbench.action.terminal.toggleFindCaseSensitive",
  "Toggle find regex in terminal": "workbench.action.terminal.toggleFindRegex",
  "Toggle find whole word in terminal":
    "workbench.action.terminal.toggleFindWholeWord",
  "Toggle terminal": "workbench.action.terminal.toggleTerminal",
  "Toggle auxiliary bar": "workbench.action.toggleAuxiliaryBar",
  "Toggle editor group layout": "workbench.action.toggleEditorGroupLayout",
  "Toggle full screen": "workbench.action.toggleFullScreen",
  "Toggle maximize editor group": "workbench.action.toggleMaximizeEditorGroup",
  "Toggle panel": "workbench.action.togglePanel",
  "Toggle sidebar visibility": "workbench.action.toggleSidebarVisibility",
  "Toggle Zen mode": "workbench.action.toggleZenMode",
  "Unpin editor": "workbench.action.unpinEditor",
  "Zoom in": "workbench.action.zoomIn",
  "Zoom out": "workbench.action.zoomOut",
  "Reset zoom": "workbench.action.zoomReset",
  "View problems": "workbench.actions.view.problems",
  "Focus banner": "workbench.banner.focusBanner",
  "Focus next action in banner": "workbench.banner.focusNextAction",
  "Focus previous action in banner": "workbench.banner.focusPreviousAction",
  "Toggle REPL in debug": "workbench.debug.action.toggleRepl",
  "Compare with clipboard": "workbench.files.action.compareWithClipboard",
  "Compare with saved": "workbench.files.action.compareWithSaved",
  "Focus open editors view": "workbench.files.action.focusOpenEditorsView",
  "Clear focus in status bar": "workbench.statusBar.clearFocus",
  "Focus first in status bar": "workbench.statusBar.focusFirst",
  "Focus last in status bar": "workbench.statusBar.focusLast",
  "Focus next in status bar": "workbench.statusBar.focusNext",
  "Focus previous in status bar": "workbench.statusBar.focusPrevious",
  "View debug": "workbench.view.debug",
  "View explorer": "workbench.view.explorer",
  "View extensions": "workbench.view.extensions",
  "View scm": "workbench.view.scm",
  "View search": "workbench.view.search",
  "Focus next with picker in breadcrumbs": "breadcrumbs.focusNextWithPicker",
  "Focus previous with picker in breadcrumbs":
    "breadcrumbs.focusPreviousWithPicker",
  "Select editor in breadcrumbs": "breadcrumbs.selectEditor",
  "Find repl input focus in list": "list.find.replInputFocus",
  "Null action in notebook cell": "notebook.cell.nullAction",
  "Select all in notebook cell output": "notebook.cell.output.selectAll",
  "Move view down": "views.moveViewDown",
  "Move view left": "views.moveViewLeft",
  "Move view right": "views.moveViewRight",
  "Move view up": "views.moveViewUp",
  "Next console in debug": "workbench.action.debug.nextConsole",
  "Previous console in debug": "workbench.action.debug.prevConsole",
  "Accept selected suggestion in terminal":
    "workbench.action.terminal.acceptSelectedSuggestion",
  "Accept selected suggestion enter in terminal":
    "workbench.action.terminal.acceptSelectedSuggestionEnter",
  "Clear terminal": "workbench.action.terminal.clear",
  "Hide suggest widget in terminal":
    "workbench.action.terminal.hideSuggestWidget",
  "Open detected link in terminal":
    "workbench.action.terminal.openDetectedLink",
  "Select next page suggestion in terminal":
    "workbench.action.terminal.selectNextPageSuggestion",
  "Select next suggestion in terminal":
    "workbench.action.terminal.selectNextSuggestion",
  "Select previous page suggestion in terminal":
    "workbench.action.terminal.selectPrevPageSuggestion",
  "Select previous suggestion in terminal":
    "workbench.action.terminal.selectPrevSuggestion",
  "Clear REPL action in debug": "workbench.debug.panel.action.clearReplAction",
  "Pause debug": "workbench.action.debug.pause",
  "Go to next command in terminal accessible buffer":
    "workbench.action.terminal.accessibleBufferGoToNextCommand",
  "Go to previous command in terminal accessible buffer":
    "workbench.action.terminal.accessibleBufferGoToPreviousCommand",
  "Rename watch expression in debug": "debug.renameWatchExpression",
  "Set variable in debug": "debug.setVariable",
  "Toggle breakpoint in debug": "debug.toggleBreakpoint",
  "Quit edit in notebook cell": "notebook.cell.quitEdit",
  "Paste in files explorer": "filesExplorer.paste",
  "Delete file": "deleteFile",
  "Go to symbol in editor": "editor.action.accessibleViewGoToSymbol",
  "Toggle screen reader accessibility mode in editor":
    "editor.action.toggleScreenReaderAccessibilityMode",
  "Close call hierarchy in editor": "editor.closeCallHierarchy",
  "Close type hierarchy in editor": "editor.closeTypeHierarchy",
  "Open and pass focus in explorer": "explorer.openAndPassFocus",
  "Cancel cut in files explorer": "filesExplorer.cancelCut",
  "Copy in files explorer": "filesExplorer.copy",
  "Cut in files explorer": "filesExplorer.cut",
  "Open file in explorer without losing focus":
    "filesExplorer.openFilePreserveFocus",
  "Go to first compressed folder": "firstCompressedFolder",
  "Accept changes in inline chat": "inlineChat.acceptChanges",
  "Go to last compressed folder": "lastCompressedFolder",
  "Move file to trash": "moveFileToTrash",
  "Go to next compressed folder": "nextCompressedFolder",
  "Go to previous compressed folder": "previousCompressedFolder",
  "Close inline remote tunnel": "remote.tunnel.closeInline",
  "Copy inline remote tunnel address": "remote.tunnel.copyAddressInline",
  "Label remote tunnel": "remote.tunnel.label",
  "Rename file": "renameFile",
  "Continue debugging": "workbench.action.debug.continue",
  "Step into debugging": "workbench.action.debug.stepInto",
  "Close reference search": "closeReferenceSearch",
  "Collapse sticky scroll list": "list.stickyScroll.collapse",
  "Select in sticky scroll list": "list.stickyScrollselect",
  "Toggle expand in sticky scroll list": "list.stickyScrolltoggleExpand",
  "Hide notifications list": "notifications.hideList",
  "Accept quick input in background": "quickInput.acceptInBackground",
  "Go back in quick input": "workbench.action.quickInputBack",
  "Navigate to next in editor picker":
    "workbench.action.quickOpenNavigateNextInEditorPicker",
  "Navigate to next in file picker":
    "workbench.action.quickOpenNavigateNextInFilePicker",
  "Navigate to next in recent files picker":
    "workbench.action.quickOpenNavigateNextInRecentFilesPicker",
  "Navigate to next in view picker":
    "workbench.action.quickOpenNavigateNextInViewPicker",
  "Navigate to previous in editor picker":
    "workbench.action.quickOpenNavigatePreviousInEditorPicker",
  "Navigate to previous in file picker":
    "workbench.action.quickOpenNavigatePreviousInFilePicker",
  "Navigate to previous in recent files picker":
    "workbench.action.quickOpenNavigatePreviousInRecentFilesPicker",
  "Navigate to previous in view picker":
    "workbench.action.quickOpenNavigatePreviousInViewPicker",
  "Select next in quick open": "workbench.action.quickOpenSelectNext",
  "Select previous in quick open": "workbench.action.quickOpenSelectPrevious",
  "Reload window": "workbench.action.reloadWindow",
  "Search workspace in terminal": "workbench.action.terminal.searchWorkspace",
  "Toggle developer tools": "workbench.action.toggleDevTools",
  "Hide notifications": "notifications.hideToasts",
  "Stop listening to chat": "workbench.action.chat.stopListening",
  "Stop reading chat item aloud": "workbench.action.chat.stopReadChatItemAloud",
  "Stop dictation in editor": "workbench.action.editorDictation.stop",
  "Stop reading aloud": "workbench.action.speech.stopReadAloud",
  "Start debugging with stop on entry":
    "extension.node-debug.startWithStopOnEntry",
  "Stage selected ranges in git": "git.stageSelectedRanges",
  "Show markdown preview": "markdown.showPreview",
  "Find references": "references-view.findReferences",
  "Unstage selected ranges in git": "git.unstageSelectedRanges",
  "Show markdown preview to side": "markdown.showPreviewToSide",
  "Go to next reference": "references-view.next",
  "Revert selected ranges in git": "git.revertSelectedRanges",
  "Go to previous reference": "references-view.prev",
  "Show call hierarchy": "references-view.showCallHierarchy",
  "Generate with Github Copilot": "github.copilot.generate",
  "Apply chat in editor": "workbench.action.chat.applyInEditor",
  "Insert code block in chat": "workbench.action.chat.insertCodeBlock",
  "Start terminal chat": "workbench.action.terminal.chat.start",
  "Accept Github Copilot cursor panel solution":
    "github.copilot.acceptCursorPanelSolution",
  "Go to previous Github Copilot panel solution":
    "github.copilot.previousPanelSolution",
  "Go to next Github Copilot panel solution":
    "github.copilot.nextPanelSolution",
  "Trigger inline suggestion": "editor.action.inlineSuggest.trigger",
  "Accept selected code action": "acceptSelectedCodeAction",
  "Hide code action widget": "hideCodeActionWidget",
  "Preview selected code action": "previewSelectedCodeAction",
  "Select next code action": "selectNextCodeAction",
  "Select previous code action": "selectPrevCodeAction",
  "Exit compare move in diff editor": "diffEditor.exitCompareMove",
  "Accept inline edits": "editor.action.inlineEdits.accept",
  // UI Toggles
  "Toggle Minimap": "editor.action.toggleMinimap",
  "Toggle Line Numbers": "editor.action.toggleLineNumbers",
  "Toggle Indent Guides": "editor.action.toggleIndentGuides",
  "Toggle Render Whitespace": "editor.action.toggleRenderWhitespace",
  "Toggle Activity Bar Visibility":
    "workbench.action.toggleActivityBarVisibility",
  "Toggle Status Bar Visibility": "workbench.action.toggleStatusbarVisibility",
  "Toggle Tabs Visibility": "workbench.action.toggleTabsVisibility",
  "Toggle Centered Layout": "workbench.action.toggleCenteredLayout",
  "Toggle Breadcrumbs": "breadcrumbs.toggle",

  // Font Size Adjustments
  "Increase Font Size": "editor.action.fontZoomIn",
  "Decrease Font Size": "editor.action.fontZoomOut",
  "Reset Font Size": "editor.action.fontZoomReset",

  // Navigation and Editor Control
  "Reveal in Explorer": "revealInExplorer",
  "Go to Next Error": "editor.action.marker.nextInFiles",
  "Go to Previous Error": "editor.action.marker.prevInFiles",
  "Duplicate Line": "editor.action.copyLinesDownAction",
  "Add Cursor Above": "editor.action.insertCursorAbove",
  "Add Cursor Below": "editor.action.insertCursorBelow",
  "Add Cursor to Line Ends": "editor.action.addCursorsToBottom",
  "Select All Occurrences": "editor.action.selectHighlights",
  "Go to Matching Bracket": "editor.action.jumpToBracket",
  "Fold All": "editor.foldAll",
  "Unfold All": "editor.unfoldAll",
  "Toggle Fold": "editor.toggleFold",
  "Open Recent": "workbench.action.openRecent",
  "Reopen Closed Editor": "workbench.action.reopenClosedEditor",
  "Close Editor": "workbench.action.closeActiveEditor",
  "Navigate Forward": "workbench.action.navigateForward",
  "Navigate Back": "workbench.action.navigateBack",
  "Select All Occurrences of Find Match": "editor.action.selectAllMatches",
  "Shrink Selection": "editor.action.smartSelect.shrink",
  "Expand Selection": "editor.action.smartSelect.expand",
  "Toggle Panel": "workbench.action.togglePanel",
  "Toggle Side Bar": "workbench.action.toggleSidebarVisibility",
  "Open Extensions View": "workbench.view.extensions",
  "Show Keyboard Shortcuts": "workbench.action.openGlobalKeybindings",
  "Toggle Full Screen": "workbench.action.toggleFullScreen",
  "Open New Window": "workbench.action.newWindow",
  "Close Window": "workbench.action.closeWindow",
  "Reload Window": "workbench.action.reloadWindow",
  "Open User Settings": "workbench.action.openSettings",
  "Toggle Activity Bar": "workbench.action.toggleActivityBarVisibility",
  "Toggle Status Bar": "workbench.action.toggleStatusbarVisibility",
  "Toggle Tabs": "workbench.action.toggleTabsVisibility",
  "Go to Next Editor": "workbench.action.nextEditor",
  "Go to Previous Editor": "workbench.action.previousEditor",
  "Close Other Editors": "workbench.action.closeOtherEditors",
  "Close Saved Editors": "workbench.action.closeSavedEditors",
  "Close Editors to the Left": "workbench.action.closeEditorsToTheLeft",
  "Close Editors to the Right": "workbench.action.closeEditorsToTheRight",
  "Focus on Editor Group Above": "workbench.action.focusAboveGroup",
  "Focus on Editor Group Below": "workbench.action.focusBelowGroup",
  "Focus on Editor Group Left": "workbench.action.focusLeftGroup",
  "Focus on Editor Group Right": "workbench.action.focusRightGroup",
  "Move Editor Left": "workbench.action.moveEditorLeftInGroup",
  "Move Editor Right": "workbench.action.moveEditorRightInGroup",
  "Open File in New Window": "workbench.action.files.openFileFolder",
  "Split Editor Left": "workbench.action.splitEditorLeft",
  "Split Editor Right": "workbench.action.splitEditorRight",
  "Split Editor Up": "workbench.action.splitEditorUp",
  "Split Editor Down": "workbench.action.splitEditorDown",
  "Navigate to Last Edit Location":
    "workbench.action.navigateToLastEditLocation",
  "Select Current Line": "expandLineSelection",
  "Insert Cursor at End of Line": "cursorLineEnd",
  "Insert Cursor at Start of Line": "cursorLineStart",
  "Add Selection to Next Find Match":
    "editor.action.addSelectionToNextFindMatch",
  "Add Selection to Previous Find Match":
    "editor.action.addSelectionToPreviousFindMatch",
  "Switch Window": "workbench.action.switchWindow",
  "Toggle Terminal Panel": "workbench.action.terminal.toggleTerminal",
  "Create New Terminal": "workbench.action.terminal.new",
  "Run Task": "workbench.action.tasks.runTask",
  "Configure Task": "workbench.action.tasks.configureTaskRunner",
  "Show Problems Panel": "workbench.actions.view.problems",
  "Go to Next Problem": "editor.action.marker.next",
  "Go to Previous Problem": "editor.action.marker.prev",
} as const;

/**
 * Custom commands that are not part of the built-in commands.
 * Usually involves multiple steps or custom logic and entity extraction.
 */
export const CustomCommands = {
  "get screenshot": "screenshot",
  "type [text]": "type",
  "type [text] and enter": "typeAndEnter",
  "keytap enter": "enter",
  "keytap tab": "tab",
  "keytap escape": "escape",
  "keytap backspace": "backspace",
  "keytap delete": "delete",
  "keytap space": "space",
  "keytap up": "up",
  "keytap down": "down",
  "keytap left": "left",
  "keytap right": "right",
  "go to line [number]": "goToLine",
  "open file [filename]": "openFile",
  "search [text]": "search",
  "replace [text] with [text]": "replace",
} as const;

export const Commands = {
  ...BuiltInCommands,
  ...CustomCommands,
} as const;
